### ISSUE TITLE
Question about qemu

### ISSUE THREAD

**Issue by cholcombe973** [kondrak/codespawn#14]
Would it be possible to apply this to qemu to generate bindings? Qemu's qapi is a json like specification which my qapi parser can turn into valid json. I've been playing around with making bindings and the challenging part is getting the code generation correct.

**Comment by kondrak** [comment]
If qapi is of the same or similar enough structure like json, then yes, this will work. Otherwise, a qapi parser will have to be added - I suppose the only way to check is to give it a shot. :) This generator was written with json and xml in mind first and foremost, so there's no guarantee everything will work out of the box at this point.

**Comment by cholcombe973** [comment]
Alright cool I think I might give this a shot to clean up my qapi_parser
crate.  I really don't like the way I have rust generating rust with just
format! Strings everywhere.

On Wed, Oct 26, 2016 at 1:15 AM, Krzysztof Kondrak <notifications@github.com
